Remove overrides for Salt Icon color
jpmorganchase/mosaic pull request #486
Opened 2023-09-15 16:21 UTC by lilyvc

This PR removes the overrides for Salt Icon color. The override is stopping the color prop from working on the Salt site, (added here: https://github.com/jpmorganchase/salt-ds/pull/2462).

2023-09-18 14:22 UTC, mark-tate commented on packages/theme/src/salt/salt.css.ts
>  });
can we remove the icon size as well ?

2023-09-18 21:07 UTC, libertymayc approved these changes

2023-09-19 07:50 UTC, DavieReid approved these changes

2023-09-19 07:58 UTC, DavieReid requested changes
This isnt building...


```
@jpmorganchase/mosaic-theme:build: ✘ [ERROR] [plugin vanilla-extract] Build failed with 1 error:
--
08:56:20.773 | @jpmorganchase/mosaic-theme:build: src/icon/icons.css.ts:5:9: error: No matching export in "src/salt/index.ts" for import "iconSizeVars"

```

2023-09-20 11:11 UTC, closed without merging